---
title: "gt missing reference"
output: pdf_document    
---

```{r}
data(cars)

library(gt)
library(gtsummary)
```

Now lets try a table in our word document. This should be @tbl-cars.

```{r}
gtcars |>
  dplyr::select(mfr, model, msrp) |>
  dplyr::slice(1:5) |>
  gt() |>
  tab_header(
    title = md("Data listing from **gtcars**"),
    subtitle = md("`gtcars` is an R dataset")
  ) |>
  tab_caption(caption = md("**gt** table example."))
```

```{r mtcars}
knitr::kable(mtcars[1:5, 1:5], caption = "A caption")
```

```{r}
set_gtsummary_theme(theme_gtsummary_journal("jama"))
tbl <- trial[c("age", "grade", "trt")] %>%
  tbl_summary(by = trt, missing = "no") %>%
  add_p()

modify_ex1 <- tbl %>%
  modify_header(label = "**Variable**", p.value = "**P**") %>%
  modify_footnote(all_stat_cols() ~ "median (IQR) for Age; n (%) for Grade") %>%
  modify_caption("**Patient Characteristics** (N = {N})") |> 
  modify_spanning_header(everything() ~ "**Treatment Received**") |> 
  as_gt() |> 
  tab_header(title = md("**this is a title**")) |> 
        tab_style(
    style = cell_text(align = "left"),
    locations = cells_title()
  ) |> 
  tab_options(table.width = pct(100))

modify_ex1

```

```{r}
modify_ex3 <-
  glm(response ~ age + grade, trial, family = binomial) %>%
  tbl_regression(exponentiate = TRUE) %>%
  modify_footnote(ci = "CI = Credible Interval", abbreviation = TRUE) |> 
  as_gt() |> 
  tab_header(title = "123455",
             subtitle = "1234") |> 
  tab_options(table.width = pct(100))


modify_ex3
```
