---
title: "bmi"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(Hmisc)
library(parameters)
```


Checking cohort BMI:

```{r}
data %>% 
  ggplot(aes(x = bmi)) +
  geom_histogram(na.rm = T)
```


```{r}
data %>% 
    ggplot(aes(sample = bmi)) + 
    stat_qq(na.rm = T) +
    stat_qq_line(na.rm = T)
```
smiling qq-plot. Data are not normally distributed. Trying log-transformation:

```{r}
data <- data %>% 
    mutate(logbmi = log(bmi))
```

```{r}
data %>% 
  ggplot(aes(x = logbmi)) +
  geom_histogram(na.rm = T)
```


```{r}
data %>% 
    ggplot(aes(sample = logbmi)) +
    stat_qq(na.rm = T) +
    stat_qq_line(na.rm = T)
```
Looks normally distributed. Backtransforming to get mean:

```{r}
data %$% 
    exp(smean.cl.normal(logbmi))
```

```{r}
data %$% 
    exp(smean.sdl(logbmi, mult = 1.96))
```

```{r}
data_liver <- data_liver %>% 
    mutate(logbmi = log(bmi))
```

Checking within liver cancer cases:

```{r}
data_liver %>% 
  ggplot(aes(x = bmi)) +
  geom_histogram(bins = 15)
```


```{r}
data_liver %>% 
    ggplot(aes(sample = bmi)) +
    stat_qq() +
    stat_qq_line()
```

```{r}
data_liver %>% 
  ggplot(aes(x = logbmi)) +
  geom_histogram(bins = 15)
```


```{r}
data_liver %>% 
    ggplot(aes(sample = logbmi)) +
    stat_qq() +
    stat_qq_line()
```

```{r}
data_liver %$% 
    exp(smean.cl.normal(logbmi))
```

Creating BMI categories:

Defining intervals and creating labels:
```{r}
cut_points <- c(-Inf, 24.99, 29.99, Inf)
labels <- c( "Normal weight", "Overweight", "Obese")
```

Creating variables:
```{r}
data <- data %>%
  mutate(bmi_category = cut(bmi, breaks = cut_points, labels = labels, include.lowest = TRUE))

```

counting n in each category and calculating %:
```{r}
data %>% 
    count(bmi_category) %>% 
    mutate(percentage = n / sum(n) * 100)
```

same for liver data:
```{r}
data_liver <- data_liver %>%
  mutate(bmi_category = cut(bmi, breaks = cut_points, labels = labels, include.lowest = TRUE))
```

```{r}
data_liver %>% 
    count(bmi_category) %>% 
    mutate(percentage = n / sum(n) * 100)
```


```{r}
t.test(data$logbmi, data_liver$logbmi) %>% 
  parameters()
```
```{r}
exp(c(3.27,
    3.36,
    -0.09))
```

