---
title: "Supplementary files"
author: "Niels Bock"
date: "4/20/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r exclusion of high alcohol consumers}
model1t_alc <- coxph(
  Surv(time = status_age, event = status == "Liver cancer") ~
    legume_daily_15 +
    updi + hpdi + animal_foods + alc_beverage_daily + total_weight_food_daily,
  data = data_alc
)

model2t_alc <- coxph(
  Surv(time = status_age, event = status == "Liver cancer") ~
    legume_daily_15 +
    updi + hpdi + animal_foods + alc_beverage_daily + total_weight_food_daily +
    sex +
    education + tdi + spouse +
    exercise + smoking_pack + alcohol_daily +
    wc,
  data = data_alc
)

model1r_alc <- coxph(
  Surv(time = status_age, event = status == "Liver cancer") ~
    legume_daily_15 + proc_meat_daily_15 +
    updi + hpdi + animal_foods + alc_beverage_daily + total_weight_food_daily,
  data = data_alc
)

model2r_alc <- coxph(
  Surv(time = status_age, event = status == "Liver cancer") ~
    legume_daily_15 + proc_meat_daily_15 +
    updi + hpdi + animal_foods + alc_beverage_daily + total_weight_food_daily +
    sex +
    education + tdi + spouse +
    exercise + smoking_pack + alcohol_daily +
    wc,
  data = data_alc
)

model1p_alc <- coxph(
  Surv(time = status_age, event = status == "Liver cancer") ~
    legume_daily_15 + red_meat_daily_15 +
    updi + hpdi + animal_foods + alc_beverage_daily + total_weight_food_daily,
  data = data_alc
)

model2p_alc <- coxph(
  Surv(time = status_age, event = status == "Liver cancer") ~
    legume_daily_15 + red_meat_daily_15 +
    updi + hpdi + animal_foods + alc_beverage_daily + total_weight_food_daily +
    sex +
    education + tdi + spouse +
    exercise + smoking_pack + alcohol_daily +
    wc,
  data = data_alc
)


m1t_alc <- model1t_alc %>%
  tbl_regression(
    exponentiate = T,
    include = legume_daily_15,
    label = legume_daily_15 ~ "Legumes for total meat",
  )

m1r_alc <- model1r_alc %>%
  tbl_regression(
    exponentiate = T,
    include = legume_daily_15,
    label = legume_daily_15 ~ "Legumes for red meat",
  )

m1p_alc <- model1p_alc %>%
  tbl_regression(
    exponentiate = T,
    include = legume_daily_15,
    label = legume_daily_15 ~ "Legumes for processed meat",
  )

m2t_alc <- model2t_alc %>%
  tbl_regression(
    exponentiate = T,
    include = legume_daily_15,
    label = legume_daily_15 ~ "Legumes for total meat",
  )

m2r_alc <- model2r_alc %>%
  tbl_regression(
    exponentiate = T,
    include = legume_daily_15,
    label = legume_daily_15 ~ "Legumes for red meat",
  )

m2p_alc <- model2p_alc %>%
  tbl_regression(
    exponentiate = T,
    include = legume_daily_15,
    label = legume_daily_15 ~ "Legumes for processed meat",
  )

row1 <- tbl_merge(list(m1t_alc, m2t_alc)) %>%
  modify_spanning_header(everything() ~ NA_character_)
row2 <- tbl_merge(list(m1r_alc, m2r_alc))
row3 <- tbl_merge(list(m1p_alc, m2p_alc))

table_alc <-
  tbl_stack(list(row1, row2, row3)) %>%
  modify_caption("**Supplementary table 3. Exclusion of high alcohol consumers. Hazard ratios for substitution of legumes for total meat, red meat and processed meat.** (N = {N})") %>%
  modify_header(label = "**15 g/day substitution**") %>%
  modify_footnote(update = everything() ~ NA, abbreviation = T) %>%
  modify_table_styling(
    column = c(p.value_1, p.value_2),
    hide = TRUE
    ) %>% 
  as_gt() %>%
  tab_spanner(
    label = "Crude",
    columns = c(estimate_1, ci_1, p.value_1)
  ) %>%
  tab_spanner(
    label = "Adjusted",
    columns = c(estimate_2, ci_2, p.value_2)
  ) %>%
  tab_footnote(
    footnote = "Adjusted for age (as underlying timescale), other food groups and total food intake to fit the substitution model.",
    locations = cells_column_spanners(spanners = "Crude")
  ) %>%
  tab_footnote(
    footnote = "Further adjusted for sex, educational level, Townsend Deprivation Index, living alone, physical activity, smoking, alcohol intake and waist circumference.",
    locations = cells_column_spanners(spanners = "Adjusted")
  )
table_alc
```

```{r exclusion of energy misreporters}
model1t_misreporter <- coxph(
  Surv(time = status_age, event = status == "Liver cancer") ~
    legume_daily_15 +
    updi + hpdi + animal_foods + alc_beverage_daily + total_weight_food_daily,
  data = data_misreporter
)

model2t_misreporter <- coxph(
  Surv(time = status_age, event = status == "Liver cancer") ~
    legume_daily_15 +
    updi + hpdi + animal_foods + alc_beverage_daily + total_weight_food_daily +
    sex +
    education + tdi + spouse +
    exercise + smoking_pack + alcohol_daily +
    wc,
  data = data_misreporter
)

model1r_misreporter <- coxph(
  Surv(time = status_age, event = status == "Liver cancer") ~
    legume_daily_15 + proc_meat_daily_15 +
    updi + hpdi + animal_foods + alc_beverage_daily + total_weight_food_daily,
  data = data_misreporter
)

model2r_misreporter <- coxph(
  Surv(time = status_age, event = status == "Liver cancer") ~
    legume_daily_15 + proc_meat_daily_15 +
    updi + hpdi + animal_foods + alc_beverage_daily + total_weight_food_daily +
    sex +
    education + tdi + spouse +
    exercise + smoking_pack + alcohol_daily +
    wc,
  data = data_misreporter
)

model1p_misreporter <- coxph(
  Surv(time = status_age, event = status == "Liver cancer") ~
    legume_daily_15 + red_meat_daily_15 +
    updi + hpdi + animal_foods + alc_beverage_daily + total_weight_food_daily,
  data = data_misreporter
)

model2p_misreporter <- coxph(
  Surv(time = status_age, event = status == "Liver cancer") ~
    legume_daily_15 + red_meat_daily_15 +
    updi + hpdi + animal_foods + alc_beverage_daily + total_weight_food_daily +
    sex +
    education + tdi + spouse +
    exercise + smoking_pack + alcohol_daily +
    wc,
  data = data_misreporter
)

m1t_misreporter <- model1t_misreporter %>%
  tbl_regression(
    exponentiate = T,
    include = legume_daily_15,
    label = legume_daily_15 ~ "Legumes for total meat",
  )

m1r_misreporter <- model1r_misreporter %>%
  tbl_regression(
    exponentiate = T,
    include = legume_daily_15,
    label = legume_daily_15 ~ "Legumes for red meat",
  )

m1p_misreporter <- model1p_misreporter %>%
  tbl_regression(
    exponentiate = T,
    include = legume_daily_15,
    label = legume_daily_15 ~ "Legumes for processed meat",
  )

m2t_misreporter <- model2t_misreporter %>%
  tbl_regression(
    exponentiate = T,
    include = legume_daily_15,
    label = legume_daily_15 ~ "Legumes for total meat",
  )

m2r_misreporter <- model2r_misreporter %>%
  tbl_regression(
    exponentiate = T,
    include = legume_daily_15,
    label = legume_daily_15 ~ "Legumes for red meat",
  )

m2p_misreporter <- model2p_misreporter %>%
  tbl_regression(
    exponentiate = T,
    include = legume_daily_15,
    label = legume_daily_15 ~ "Legumes for processed meat",
  )

row1 <- tbl_merge(list(m1t_misreporter, m2t_misreporter)) %>%
  modify_spanning_header(everything() ~ NA_character_)
row2 <- tbl_merge(list(m1r_misreporter, m2r_misreporter))
row3 <- tbl_merge(list(m1p_misreporter, m2p_misreporter))

table_misreporter <-
  tbl_stack(list(row1, row2, row3)) %>%
  modify_caption("**Supplementary table 4. Exclusion of food intake misreporters. Hazard ratios for substitution of legumes for total meat, red meat and processed meat.** (N = {N})") %>%
  modify_header(label = "**15 g/day substitution**") %>%
  modify_footnote(update = everything() ~ NA, abbreviation = T) %>%
  modify_table_styling(
    column = c(p.value_1, p.value_2),
    hide = TRUE
    ) %>% 
  as_gt() %>%
  tab_spanner(
    label = "Crude",
    columns = c(estimate_1, ci_1, p.value_1)
  ) %>%
  tab_spanner(
    label = "Adjusted",
    columns = c(estimate_2, ci_2, p.value_2)
  ) %>%
  tab_footnote(
    footnote = "Adjusted for age (as underlying timescale), other food groups and total food intake to fit the substitution model.",
    locations = cells_column_spanners(spanners = "Crude")
  ) %>%
  tab_footnote(
    footnote = "Further adjusted for sex, educational level, Townsend Deprivation Index, living alone, physical activity, smoking, alcohol intake and waist circumference.",
    locations = cells_column_spanners(spanners = "Adjusted")
  )
table_misreporter
```

```{r 3 or more compled diet questionnaires}
model1t_3_ques_comp <- coxph(
  Surv(time = status_age, event = status == "Liver cancer") ~
    legume_daily_15 +
    updi + hpdi + animal_foods + alc_beverage_daily + total_weight_food_daily,
  data = data_3_ques_comp
)

model2t_3_ques_comp <- coxph(
  Surv(time = status_age, event = status == "Liver cancer") ~
    legume_daily_15 +
    updi + hpdi + animal_foods + alc_beverage_daily + total_weight_food_daily +
    sex +
    education + tdi + spouse +
    exercise + smoking_pack + alcohol_daily +
    wc,
  data = data_3_ques_comp
)

model1r_3_ques_comp <- coxph(
  Surv(time = status_age, event = status == "Liver cancer") ~
    legume_daily_15 + proc_meat_daily_15 +
    updi + hpdi + animal_foods + alc_beverage_daily + total_weight_food_daily,
  data = data_3_ques_comp
)

model2r_3_ques_comp <- coxph(
  Surv(time = status_age, event = status == "Liver cancer") ~
    legume_daily_15 + proc_meat_daily_15 +
    updi + hpdi + animal_foods + alc_beverage_daily + total_weight_food_daily +
    sex +
    education + tdi + spouse +
    exercise + smoking_pack + alcohol_daily +
    wc,
  data = data_3_ques_comp
)

model1p_3_ques_comp <- coxph(
  Surv(time = status_age, event = status == "Liver cancer") ~
    legume_daily_15 + red_meat_daily_15 +
    updi + hpdi + animal_foods + alc_beverage_daily + total_weight_food_daily,
  data = data_3_ques_comp
)

model2p_3_ques_comp <- coxph(
  Surv(time = status_age, event = status == "Liver cancer") ~
    legume_daily_15 + red_meat_daily_15 +
    updi + hpdi + animal_foods + alc_beverage_daily + total_weight_food_daily +
    sex +
    education + tdi + spouse +
    exercise + smoking_pack + alcohol_daily +
    wc,
  data = data_3_ques_comp
)

m1t_3_ques_comp <- model1t_3_ques_comp %>%
  tbl_regression(
    exponentiate = T,
    include = legume_daily_15,
    label = legume_daily_15 ~ "Legumes for total meat",
  )

m1r_3_ques_comp <- model1r_3_ques_comp %>%
  tbl_regression(
    exponentiate = T,
    include = legume_daily_15,
    label = legume_daily_15 ~ "Legumes for red meat",
  )

m1p_3_ques_comp <- model1p_3_ques_comp %>%
  tbl_regression(
    exponentiate = T,
    include = legume_daily_15,
    label = legume_daily_15 ~ "Legumes for processed meat",
  )

m2t_3_ques_comp <- model2t_3_ques_comp %>%
  tbl_regression(
    exponentiate = T,
    include = legume_daily_15,
    label = legume_daily_15 ~ "Legumes for total meat",
  )

m2r_3_ques_comp <- model2r_3_ques_comp %>%
  tbl_regression(
    exponentiate = T,
    include = legume_daily_15,
    label = legume_daily_15 ~ "Legumes for red meat",
  )

m2p_3_ques_comp <- model2p_3_ques_comp %>%
  tbl_regression(
    exponentiate = T,
    include = legume_daily_15,
    label = legume_daily_15 ~ "Legumes for processed meat",
  )

row1 <- tbl_merge(list(m1t_3_ques_comp, m2t_3_ques_comp)) %>%
  modify_spanning_header(everything() ~ NA_character_)
row2 <- tbl_merge(list(m1r_3_ques_comp, m2r_3_ques_comp))
row3 <- tbl_merge(list(m1p_3_ques_comp, m2p_3_ques_comp))

table_3_ques_comp <-
  tbl_stack(list(row1, row2, row3)) %>%
  modify_caption("**Supplementary table 5. Participant who completed three or more diet questionnaires. Hazard ratios for substitution of legumes for total meat, red meat and processed meat.** (N = {N})") %>%
  modify_header(label = "**15 g/day substitution**") %>%
  modify_footnote(update = everything() ~ NA, abbreviation = T) %>%
  modify_table_styling(
    column = c(p.value_1, p.value_2),
    hide = TRUE
    ) %>% 
  as_gt() %>%
  tab_spanner(
    label = "Crude",
    columns = c(estimate_1, ci_1, p.value_1)
  ) %>%
  tab_spanner(
    label = "Adjusted",
    columns = c(estimate_2, ci_2, p.value_2)
  ) %>%
  tab_footnote(
    footnote = "Adjusted for age (as underlying timescale), other food groups and total food intake to fit the substitution model.",
    locations = cells_column_spanners(spanners = "Crude")
  ) %>%
  tab_footnote(
    footnote = "Further adjusted for sex, educational level, Townsend Deprivation Index, living alone, physical activity, smoking, alcohol intake and waist circumference.",
    locations = cells_column_spanners(spanners = "Adjusted")
  )
table_3_ques_comp
```

