---
output:
  bookdown::pdf_book:
    base_format: rticles::mdpi_article
    extra_dependencies: longtable, fancyhdr
header-includes:
  - \usepackage{caption}
  - \captionsetup{font=small,justification=raggedright,singlelinecheck=false}
---

```{=tex}
\appendixtitles{no}
\appendixstart
\appendix
\section[\appendixname]{}
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      out.extra = "")
library(here)
library(gt)
library(gtsummary)
library(tidyverse)
library(survival)
targets::tar_config_set(store = here::here("_targets"))
data_hcc <- targets::tar_read(data_with_hcc)
data_icc <- targets::tar_read(data_with_icc)
source(here("R", "table-cancer-type.R"))
source(here("R", "dag-code.R"))
source(here("R", "table-food-groups.R"))
source(here("R", "table-legume-quartiles.R"))
source(here("R", "table_sens.R"))
```

\clearpage

```{r fig2, out.width = "100%", fig.env = "figure*", fig.align = 'center', fig.cap = "Simplified directed acyclic graph (DAG) visualizing the hypothesised causal relationship between replacing red meat with legumes and liver cancer based on assumptions of biasing paths. Red nodes represent confounders. Square nodes represent the minimal sufficient adjustment set for estimating the effect of replacing red meat with legumes on liver cancer. Shadowed arrows represent biasing paths. DAG terminology demands visualisation of all hypothesized correlating relationships between variables, typically resulting in complex and hard-to-follow illustrations. To improve readability, inter-covariate arrows are hidden in the above DAG."}
dag
```

```{r food-group}
food_group_table
```

```{r cancer}
table_cancer_type %>% 
  tab_options(latex.use.longtable = FALSE,
              latex.tbl.pos = "t")
```

```{r legume}
table_legume %>% 
  tab_options(latex.use.longtable = FALSE,
              latex.tbl.pos = "t")
```

```{=tex}
\clearpage
\startlandscape
```
```{r sens}
table_sens %>% 
  tab_options(latex.use.longtable = FALSE,
              latex.tbl.pos = "t")
```

\finishlandscape
