---
title: "Substitution of red meat with legumes and risk of primary liver cancer in UK Biobank participants: a prospective cohort study"
author:
  - name: Niels Bock
    affil: 1
    orcid: 0009-0005-7373-1589
  - name: Fie Langmann
    affil: 1
    orcid: 0000-0003-3474-9346
  - name: Luke W. Johnston
    affil: 1, 2
    orcid: 0000-0003-4169-2616
  - name: Daniel B. Ibsen
    affil: 1, 2, 3, 4
    orcid: 0000-0002-7038-4770
  - name: Christina C. Dahm
    affil: 1, *
    orcid: 0000-0003-0481-2893
affiliation:
  - num: 1
    address: |
      Department of Public Health, 
      Aarhus University,
      Aarhus, Denmark
  - num: 2
    address: |
      Steno Diabetes Center Aarhus,
      Aarhus University Hospital,
      Aarhus N, Denmark
  - num: 3
    address: |
      Department of Nutrition, Exercise and Sports,
      University of Copenhagen,
      Copenhagen, Denmark
  - num: 4
    address: |
      MRC Epidemiology Unit, School of Clinical Medicine,
      University of Cambridge,
      Cambridge, United Kingdom
# author citation list in chicago format
authorcitation: |
  Bock, N; Langmann, F; Johnston, LW; Ibsen, DB; Dahm, CC
correspondence: |
  CCD@ph.au.dk.
# document options
journal: nutrients
type: article
status: submit
# front matter
abstract: |
  Purpose: Primary liver cancer is on the rise worldwide, partially due to poor diets and sedentary lifestyles. Shifting to more plant-based diets may lower the risk. We aimed to estimate the effect of replacing unprocessed red meat, processed red meat and total red meat with legumes on primary liver cancer in a free-living population. Methods: We analyzed data from 126,744 UK Biobank participants who completed $\geq$ 2 24-hour diet recalls. Baseline characteristics were collected from the initial assessment visit. Information on liver cancer diagnoses was collected via external linkage to inpatient hospital episodes or central cancer registries. Cox proportional hazards regression models were used to estimate substitution of 15 g/day of legumes with 15 g/day of total red meat, unprocessed red meat or processed red meat on liver cancer risk, using the leave-one-out food substitution model.  Results: During a median follow-up time of 11.3 years, 173 participants developed liver cancer. In the fully adjusted models, no association was observed when substituting 15 g/day of legumes with total red meat (HR: 1.02 (95% CI 0.96-1.08)), unprocessed red meat (HR: 1.00 (95% CI 0.94-1.06)) or processed red meat (HR: 1.09 (95% CI 0.99-1.21)). Conclusion: Overall, little evidence of an association between replacing red meat with legumes and liver cancer was observed. Further research in larger study populations with longer follow-up time is warranted.
# back matter
keywords: |
  Food Substitutions; liver cancer; red meat; legumes.
output:
  bookdown::pdf_book:
    base_format: rticles::mdpi_article
    extra_dependencies: longtable, fancyhdr
header-includes:
  - \usepackage{caption}
  - \captionsetup{font=small,justification=raggedright,singlelinecheck=false}
  - \captionsetup[table]{labelformat=default, labelsep=period}
  - \captionsetup[figure]{labelformat=default, labelsep=period}
  - \renewcommand{\thetable}{S\arabic{table}}
  - \renewcommand{\thefigure}{S\arabic{figure}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      out.extra = "")
library(here)
library(gt)
library(gtsummary)
library(tidyverse)
library(survival)
targets::tar_config_set(store = here::here("_targets"))
data <- targets::tar_read(data_main)
data_hcc <- targets::tar_read(data_with_hcc)
data_icc <- targets::tar_read(data_with_icc)
data_alc <- targets::tar_read(data_with_alc)
data_misreporter <- targets::tar_read(data_with_misreporter)
data_3_ques_comp <- targets::tar_read(data_with_3_ques_comp)
data_liver_disease <- targets::tar_read(data_without_liver_disease)
data_any_cancer <- targets::tar_read(data_without_cancer)
data_death <- targets::tar_read(data_with_death)
source(here("R", "table-cancer-type.R"))
source(here("R", "dag-code.R"))
source(here("R", "table-food-groups.R"))
source(here("R", "table-legume-quartiles.R"))
source(here("R", "table-sens.R"))
```

\clearpage

# Supplementary materials {#sec1}

```{r fig2, out.width = "100%", fig.env = "figure*", fig.align = 'center', fig.pos="h", fig.cap = "Simplified directed acyclic graph (DAG) visualizing the hypothesised causal relationship between replacing red meat with legumes and liver cancer based on assumptions of biasing paths. Red nodes represent confounders. Square nodes represent the minimal sufficient adjustment set for estimating the effect of replacing red meat with legumes on liver cancer. Shadowed arrows represent biasing paths. DAG terminology demands visualisation of all hypothesized correlating relationships between variables, typically resulting in complex and hard-to-follow illustrations. To improve readability, inter-covariate arrows are hidden in the above DAG."}
dag
```

```{r food-group}
food_group_table %>% 
  tab_options(latex.use.longtable = FALSE,
              latex.tbl.pos = "t")
```

```{r cancer}
table_cancer_type %>% 
  tab_options(latex.use.longtable = FALSE,
              latex.tbl.pos = "t")
```

```{r legume}
table_legume %>% 
  tab_options(latex.use.longtable = FALSE,
              latex.tbl.pos = "t")
```

```{=tex}
\clearpage
\startlandscape
```
```{r sens}
table_sens %>% 
  tab_options(latex.use.longtable = FALSE,
              latex.tbl.pos = "t")
```

\finishlandscape
